export const slides = [
    {
      id: 1,
      title: "Modern Architecture",
      subtitle: "Sleek & Sustainable Designs",
      description: "Exploring the harmony between cutting-edge design and environmental consciousness in urban landscapes.",
      bgColor: "bg-slate-900",
      textColor: "text-white",
      fontFamily: "font-serif",
    },
    {
      id: 2,
      title: "Digital Horizons",
      subtitle: "The Future of Connectivity",
      description: "Dive into the evolving world of technology and how it shapes our interactions and daily lives.",
      bgColor: "bg-blue-800",
      textColor: "text-white",
      fontFamily: "font-sans",
    },
    {
      id: 3,
      title: "Minimalist Living",
      subtitle: "Simplicity in Every Detail",
      description: "Discover the beauty of less, focusing on intentionality and finding peace in uncluttered spaces.",
      bgColor: "bg-emerald-900",
      textColor: "text-white",
      fontFamily: "font-mono",
    },
    {
      id: 4,
      title: "Culinary Journeys",
      subtitle: "Flavors Around the World",
      description: "Embark on a taste adventure, exploring diverse cuisines and the stories behind traditional dishes.",
      bgColor: "bg-rose-900",
      textColor: "text-white",
      fontFamily: "font-serif",
    },
    {
      id: 5,
      title: "Cosmic Wonders",
      subtitle: "Exploring the Universe",
      description: "Gaze into the vastness of space, uncovering the mysteries of distant galaxies and celestial phenomena.",
      bgColor: "bg-indigo-950",
      textColor: "text-white",
      fontFamily: "font-sans",
    },
    {
      id: 6,
      title: "Urban Rhythms",
      subtitle: "The Pulse of the City",
      description: "Feel the energy of metropolitan life, capturing the dynamic spirit and diverse cultures of cityscapes.",
      bgColor: "bg-amber-800",
      textColor: "text-white",
      fontFamily: "font-mono",
    },
  ];